blog/urls.py
# -*- coding: utf-8 -*-
"""Tablica ze sciezkami w projekcie"""
from django.urls import path, include
from .views import (
    UniversityListView,
    UniversityDetailView,
    CourseListView,
    CourseDetailView,
    comparison,
    ulotka,

    CourseCreateView,
    CourseDeleteView,
    CourseUpdateView,
    UniversityCreateView,
    UniversityDeleteView,
    UniversityUpdateView,
)

urlpatterns = [
    path('', ulotka, name='blog-home'),

    path('universities', UniversityListView.as_view(),
         name='blog-universities'),
    path('universities/<int:pk>', UniversityDetailView.as_view(),
         name='university-detail'),
    path('courses', CourseListView.as_view(), name='blog-courses'),
    path('courses/<int:pk>', CourseDetailView.as_view(), name='course-detail'),

    path('comparison', comparison, name='blog-comparison'),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),

    path('courses/new/', CourseCreateView.as_view(), name='course-create'),
    path('courses/<int:pk>/update/', CourseUpdateView.as_view(),
         name='course-update'),
    path('courses/<int:pk>/delete/', CourseDeleteView.as_view(),
         name='course-delete'),

    path('universities/new/', UniversityCreateView.as_view(),
         name='university-create'),
    path('universities/<int:pk>/update/', UniversityUpdateView.as_view(),
         name='university-update'),
    path('universities/<int:pk>/delete/', UniversityDeleteView.as_view(),
         name='university-delete'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


class University(models.Model):
    """Model z bazy danych dla uniwersytetu"""
    types = (('politechnika', 'Politechnika'),
             ('uniwersytet ogolny', 'Uniwersytet Ogólny'),
             ('uniwersytet medyczny', 'Uniwersytet Medyczny'),
             ('uniwersytet ekonomiczny', 'Uniwersytet Ekonomiczny'),
             ('uniwersytet przyrodniczy', 'Uniwersytet Przyrodniczy'))

    nazwa = models.CharField(max_length=100)
    lokacja = models.CharField(max_length=100)
    date_posted = models.DateTimeField(default=timezone.now)
    typ = models.CharField(max_length=100, choices=types)
    national_ranking = models.IntegerField()
    website_url = models.URLField()

    def __str__(self):
        return self.nazwa

    # Odnosnik do szczegolowego widoku dla danego obiektu
    def get_absolute_url(self):
        return reverse('university-detail', kwargs={'pk': self.pk})


class Course(models.Model):
    """Model z bazy danych dla kierunku"""
    types = (('stacjonarne', 'Stacjonarne'),
             ('niestacjonarne', 'Niestacjonarne'))

    types1 = (('licencjat', 'Licencjat'),
              ('inzynier', 'Inzynier'),
              ('magister', 'Magister'))

    nazwa = models.CharField(max_length=100)
    uniwersytet = models.ForeignKey(University, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    description = models.TextField()
    tryb = models.CharField(max_length=100, choices=types)
    tytul = models.CharField(max_length=100, choices=types1)
    grade = models.IntegerField()
    semesters = models.IntegerField()
    department = models.CharField(max_length=100)
    m_to_w_ratio = models.IntegerField(default=55)
    international_ratio = models.IntegerField(default=55)
    would_choose_again = models.IntegerField(default=55)
    avg_salary = models.IntegerField(default=55)
    function = models.IntegerField(default=55)

    def __str__(self):
        return self.nazwa

    # Odnosnik do szczegolowego widoku dla danego obiektu
    def get_absolute_url(self):
        return reverse('course-detail', kwargs={'pk': self.pk})

blog/views.py
from .models import University, Course
from blog.components.progressBar import create_progress
from blog.components.courseGraph import create_graph
from blog.components.button import create_checkbox, is_created
from .filters import CourseFilter, UniversityFilter
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)


def ulotka(request):
    """Widok startowy"""
    return render(request, 'blog/ulotka.html')


def comparison(request):
    """Zwraca widok dla wykresu z porownaniami"""
    is_created()
    return render(request, 'blog/comparison.html', None)


class UniversityListView(ListView):
    """Widok dla listy uniwersytetow"""
    model = University
    template_name = 'blog/university.html'
    context_object_name = 'universities'
    ordering = ['nazwa']
    paginate_by = 10

    def get_context_data(self, **kwargs):
        """Zwraca kontekst przy wywolywaniu template'a
        Filtruje wedlug wyszukiwarki"""
        context = super().get_context_data(**kwargs)
        context['filter'] = UniversityFilter(self.request.GET,
                                             queryset=self.get_queryset())
        return context


class UniversityDetailView(DetailView):
    """Widok dla uniwersytetu"""
    model = University


class CourseListView(ListView):
    """Widok dla listy kierunkow"""
    model = Course
    template_name = 'blog/course.html'
    context_object_name = 'courses'
    ordering = ['nazwa']
    paginate_by = 10

    def get_context_data(self, *args, object_list=None, **kwargs):
        """Zwraca kontekst przy wywolywaniu template'a
        Tworzy checkboxy dla kierunkow
        Filtruje wedlug wyszukiwarki"""
        objects = self.get_queryset().all()
        create_checkbox(objects)
        context = super().get_context_data(**kwargs)
        context['filter'] = CourseFilter(self.request.GET,
                                         queryset=self.get_queryset())
        return context


class CourseDetailView(DetailView):
    """Widok dla kierunku"""
    model = Course

    def get_context_data(self, **kwargs):
        """Zwraca kontekst przy wywolywaniu template'a
        Tworzy wykres i paski postepu
        """
        create_graph(self.get_object())
        create_progress(self.get_object())
        context = super().get_context_data(**kwargs)
        return context


class CourseCreateView(LoginRequiredMixin, CreateView):
    """Widok dla tworzenia kierunku"""
    model = Course
    fields = ['nazwa', 'uniwersytet', 'description',
              'tryb', 'tytul', 'grade', 'semesters',
              'department', 'm_to_w_ratio', 'international_ratio',
              'would_choose_again', 'avg_salary', 'function']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class CourseUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Widok dla zmieniania kierunku"""
    model = Course
    fields = ['nazwa', 'uniwersytet', 'description',
              'tryb', 'tytul', 'grade', 'semesters',
              'department', 'm_to_w_ratio', 'international_ratio',
              'would_choose_again', 'avg_salary', 'function']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        return True


class CourseDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Widok dla usuwania kierunku"""
    model = Course
    success_url = '/'

    def test_func(self):
        return True


class UniversityCreateView(LoginRequiredMixin, CreateView):
    """Widok dla tworzenia uniwersytetu"""
    model = University
    fields = ['nazwa', 'lokacja', 'typ',
              'national_ranking', 'website_url']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UniversityUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Widok dla zmieniania uniwersytetu"""
    model = University
    fields = ['nazwa', 'lokacja', 'typ',
              'national_ranking', 'website_url']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        return True


class UniversityDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Widok dla usuwania uniwersytetu"""
    model = University
    success_url = '/'

    def test_func(self):
        return True

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">University Finder</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog-universities' %}">Uniwersytety</a>
              <a class="nav-item nav-link" href="{% url 'blog-courses' %}">Kierunki</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'course-create' %}">Dodaj kierunek</a>
                  <a class="nav-item nav-link" href="{% url 'university-create' %}">Dodaj uniwersytet</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Wyloguj</a>
              {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Zaloguj</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md">
          {% if messages %}
              {% for message in messages %}
                  <div class="alert alert-{{message.tags}}">
                      {{ message }}
                  </div>
              {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/comparison.html
{% extends "blog/base.html" %}
{% block content %}
    {% load plotly_dash %}
    {% plotly_app name="Comparison" ratio=10 %}
{% endblock content %}

blog/templates/blog/course.html
{% extends "blog/base.html" %}
{% load bootstrap %}
{% block content %}
    <form method="GET">
        {{ filter.form|bootstrap }}
        <button type="submit" class="btn btn-primary">Wyszukaj</button>
    </form>
    <div><p></p></div>
    <div class="container-fluid">

        {% load plotly_dash %}
        {% plotly_app name="Button" ratio=0.05 %}
        <a href="comparison"> Sprawdz porownanie </a>
    </div>
    {% for course in filter.qs %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2"
                       href="{% url 'university-detail' course.uniwersytet.id %}"
                    >{{ course.uniwersytet.nazwa }}</a>
                    <small class="
                       text-muted">{{ course.date_posted|date:"d F, Y" }}</small>
                </div>
                <h2>
                    {% with course.id|stringformat:"s" as id %}
                        {% with "Check"|add:id as check_id %}
                            {% plotly_app name=check_id ratio=0.025 %}
                        {% endwith %}
                    {% endwith %}
                    <a class="article-title"
                       href="{% url 'course-detail' course.id %}">{{ course.nazwa }}</a>
                </h2>
                <p class="article-description">{{ course.description }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

blog/templates/blog/course_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
	<div class="content-section">
    	<form method="POST">
        	{% csrf_token %}
        	<fieldset class="form-group">
            	<legend class="border-bottom mb-4">Usun kierunek</legend>
            	<h2>Czy na pewno chcesz usunac ten kierunek "{{ object.nazwa }}?"</h2>
        	</fieldset>
        	<div class="form-group">
            	<button class="btn btn-outline-danger" type="submit">Tak</button>
            	<a class="btn btn-outline-secondary" href="{% url 'course-detail' object.id %}">Anuluj</a>
        	</div>
    	</form>
	</div>
{% endblock content %}

blog/templates/blog/course_detail.html
{% extends "blog/base.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2"
                       href="{% url 'university-detail' course.uniwersytet.id %}"
                    >{{ course.uniwersytet.nazwa }}</a>
                {% if user.is_authenticated %}
                    				<div>
                        				<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'course-update' object.id %}">Update</a>
                        				<a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'course-delete' object.id %}">Delete</a>
                   				</div>
                {% endif %}
                <small class="text-muted">{{ object.date_posted|date:"d F, Y" }}</small>
            </div>
            <h2 class="article-title">{{ object.nazwa }}</h2>
            <p class="article-content"> {{ object.department }}</p>
            <p class="article-content"> Stopien {{ object.grade }}</p>
            <p class="article-content"> Tryb {{ object.tryb }}</p>
            <p class="article-content"> Ilosc semestrow: {{ object.semesters }}</p>
            <p class="article-content"> Tytul {{ object.tytul }}</p>
            <p class="article-content">{{ object.description }}</p>
        </div>

    </article>
    {% load plotly_dash %}
    {% plotly_app name="Progress" ratio=0.2 %}
    {% plotly_app name="CourseGraph" ratio=0.65 %}

{% endblock content %}

blog/templates/blog/course_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
    	<form method="POST">
        	{% csrf_token %}
        	<fieldset class="form-group">
            	<legend class="border-bottom mb-4">Kierunek</legend>
            	{{ form|crispy }}
        	</fieldset>
        	<div class="form-group">
            	<button class="btn btn-outline-info" type="submit">Dodaj</button>
        	</div>
    	</form>
	</div>
{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load bootstrap %}
{% block content %}
    <form method="GET">
            
                {{ filter.form|bootstrap }}
            
            <button type="submit" class="btn btn-primary">Search</button>
    </form>
    {% load plotly_dash %}
    {% plotly_app name="Button" ratio=0.05 %}
    <a href="comparison"> Sprawdz porownanie </a>
    {% plotly_app name="Checkall" ratio=0.025 %}
	{% for post in filter.qs %}
			<article class="media content-section">
				<div class="media-body">
					<div class="article-metadata">
						<a class="mr-2" href="#">{{ post.uniwersytet }}</a>
						<small class="text-muted">{{ post.tryb }}</small>
						<small class="text-muted">{{ post.tytul }}</small>
						<small class="text-muted">{{ post.date_posted|date:"d F, Y" }}</small>
					</div>
					<h2>
					{% with post.id|stringformat:"s" as id %}
                        {% with "Check"|add:id as check_id %}
                            {% plotly_app name=check_id ratio=0.025 %}
                        {% endwith %}
                    {% endwith %}
					<a class="article-title" href="{% url 'course-detail' post.id %}">{{ post.nazwa }}</a>
					</h2>
					<p class="article-content">{{ post.description }}</p>
				</div>
			</article>
	{% endfor %}
	{% if is_paginated %}
	
    	{% if page_obj.has_previous %}
        	<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        	<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    	{% endif %}
    	
    	{% for num in page_obj.paginator.page_range %}
        	{% if page_obj.number == num %}
            	<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        	{% endif %}
    	{% endfor %}
    	
    	{% if page_obj.has_next %}
        	<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        	<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    	{% endif %}
    	
	{% endif %}
{% endblock content %}

blog/templates/blog/unis.html
{% extends "blog/base.html" %}
{% load bootstrap %}
{% block content %}
    <form method="GET">
            
                {{ filter.form|bootstrap }}
            
            <button type="submit" class="btn btn-primary">Search</button>
    </form>
	{% for post in filter.qs %}
			<article class="media content-section">
				<div class="media-body">
					<div class="article-metadata">
						<a class="mr-2" href="#">{{ post.lokacja }}</a>
						<small class="text-muted">{{ post.typ }}</small>
						<small class="text-muted">{{ post.date_posted|date:"d F, Y" }}</small>
					</div>
					<h2><a class="article-title" href="{% url 'university-detail' post.id %}">{{ post.nazwa }}</a></h2>
				</div>
			</article>
	{% endfor %}
	{% if is_paginated %}
	
    	{% if page_obj.has_previous %}
        	<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        	<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    	{% endif %}
    	
    	{% for num in page_obj.paginator.page_range %}
        	{% if page_obj.number == num %}
            	<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        	{% endif %}
    	{% endfor %}
    	
    	{% if page_obj.has_next %}
        	<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        	<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    	{% endif %}
    	
	{% endif %}
{% endblock content %}

blog/templates/blog/university.html
{% extends "blog/base.html" %}
{% load bootstrap %}
{% block content %}
    <form method="GET">
        {{ filter.form|bootstrap }}
        <button type="submit" class="btn btn-primary">Wyszukaj</button>
    </form>
    {% for university in filter.qs %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <small class="text-muted">{{ university.lokacja }},</small>
                    <small class="text-muted">{{ university.typ }}</small>
                    <small class="text-muted">{{ university.date_posted|date:"d F, Y" }}</small>
                </div>
                <h2><a class="article-title"
                       href="{% url 'university-detail' university.id %}">{{ university.nazwa }}</a>
                </h2>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

blog/templates/blog/university_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
	<div class="content-section">
    	<form method="POST">
        	{% csrf_token %}
        	<fieldset class="form-group">
            	<legend class="border-bottom mb-4">Usun uniwersytet</legend>
            	<h2>Czy na pewno chcesz usunac ten uiwersytet "{{ object.nazwa }}?"</h2>
        	</fieldset>
        	<div class="form-group">
            	<button class="btn btn-outline-danger" type="submit">Tak</button>
            	<a class="btn btn-outline-secondary" href="{% url 'university-detail' object.id %}">Anuluj</a>
        	</div>
    	</form>
	</div>
{% endblock content %}

blog/templates/blog/university_detail.html
{% extends "blog/base.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                {% if user.is_authenticated %}
                    				<div>
                        				<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'university-update' object.id %}">Update</a>
                        				<a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'university-delete' object.id %}">Delete</a>
                   				</div>
                {% endif %}
                <small class="text-muted">{{ object.date_posted|date:"d F, Y" }}</small>
            </div>
            <h2 class="article-title">{{ object.nazwa }}</h2>
            <p class="article-content"> Typ: {{ object.typ }}</p>
            <p class="article-content"> Lokacja: {{ object.lokacja }}</p>
            <p class="article-content"
            > Miejsce w rankingu narodowym: {{ object.national_ranking }}</p>
            <p class="article-content"> Strona uniwersytetu: <a
                    href={{ object.website_url }}> {{ object.website_url }} </a>
            </p>
        </div>
    </article>
    <h2 class="article-title"> Lista kursow:</h2>
    {% for course in object.course_set.all %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <small class="text-muted">{{ course.date_posted|date:"d F, Y" }}</small>
                </div>
                <h2>
                    <a class="article-title"
                       href="{% url 'course-detail' course.id %}">{{ course.nazwa }}</a>
                </h2>
                <p class="article-description">{{ course.description }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

blog/templates/blog/university_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
    	<form method="POST">
        	{% csrf_token %}
        	<fieldset class="form-group">
            	<legend class="border-bottom mb-4">Uniwersytet</legend>
            	{{ form|crispy }}
        	</fieldset>
        	<div class="form-group">
            	<button class="btn btn-outline-info" type="submit">Dodaj</button>
        	</div>
    	</form>
	</div>
{% endblock content %}